[package]
name = "senpi-desktop-backend-x11"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[target.'cfg(target_os = "linux")'.dependencies]
image.workspace = true
libc.workspace = true
senpi-desktop-core = { path = "../senpi-desktop-core" }
x11rb.workspace = true
xkeysym.workspace = true
